In [2]:
import pandas as pd

df_wine = pd.read_csv('./python-machine-learning-book-2nd-edition-master/code/ch04/wine.data')
df_wine.columns = ['Class label', 'Alcohol', 'Malic acid', 'Ash',
                   'Alcalinity of ash', 'Magnesium', 'Total phenols',
                   'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins',
                   'Color intensity', 'Hue', 'OD280/OD315 of diluted wines',
                   'Proline']
df_wine.head()

,Class label,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df_wine.iloc[:,1:].values
y = df_wine.iloc[:,0].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1,stratify=y)

stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)

In [6]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(penalty='l1', C=1.0)

lr.fit(X_train_std, y_train)

print('Training accuracy:', lr.score(X_train_std, y_train))

print('Test accuracy:', lr.score(X_test_std, y_test))

print(lr.get_params())

Training accuracy: 1.0
Test accuracy: 0.9814814814814815
{'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'max_iter': 100, 'multi_class': 'ovr', 'n_jobs': 1, 'penalty': 'l1', 'random_state': None, 'solver': 'liblinear', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}

In [9]:
pd.DataFrame(lr.coef_)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,1.469825,0.000000,0.515561,-1.310787,0.000000,0.0,1.241228,0.000000,0.000000,0.000000,0.000000,0.689006,2.167661
1,-1.855350,-0.314831,-1.182643,0.688202,-0.154014,0.0,0.605017,0.000000,0.154253,-1.207521,1.254040,0.000000,-2.054157
2,0.000000,0.226122,0.573930,0.000000,0.121977,0.0,-2.561352,-0.138703,0.000000,1.625082,-0.902494,-0.396796,0.000000

In [17]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(penalty='l1', C=1.0, multi_class='multinomial', solver='saga', max_iter=1000)
#'if mulinomial'= not OvA , then solver shoud be 'saga' and max_iter shoud be increase

lr.fit(X_train_std, y_train)

print('Training accuracy:', lr.score(X_train_std, y_train))

print('Test accuracy:', lr.score(X_test_std, y_test))

pd.DataFrame(lr.coef_)
pd.DataFrame(lr.predict_proba(X_train_std))

Training accuracy: 1.0
Test accuracy: 0.9814814814814815

            0         1         2
0    0.846571  0.129553  0.023876
1    0.000792  0.996187  0.003021
2    0.007919  0.075387  0.916694
3    0.010487  0.958174  0.031339
4    0.999846  0.000018  0.000137
5    0.000929  0.002311  0.996760
6    0.005707  0.004264  0.990029
7    0.980004  0.012148  0.007847
8    0.924846  0.063114  0.012040
9    0.948736  0.048522  0.002743
10   0.001829  0.998052  0.000119
11   0.036828  0.900275  0.062897
12   0.002626  0.002270  0.995104
13   0.001503  0.998356  0.000141
14   0.002490  0.006467  0.991043
15   0.001625  0.997684  0.000691
16   0.006700  0.993238  0.000062
17   0.900024  0.092355  0.007621
18   0.000287  0.999701  0.000012
19   0.003894  0.004700  0.991406
20   0.001867  0.068371  0.929762
21   0.044834  0.954786  0.000380
22   0.032059  0.009297  0.958644
23   0.034521  0.052286  0.913193
24   0.021366  0.976253  0.002380
25   0.000357  0.999097  0.000546
26   0.006544  0.001129  0.992327
27   0.004586  0.002157  0.993257
28   0.970764  0.028293  0.000943
29   0.962457  0.028845  0.008698
..        ...       ...       ...
93   0.104073  0.892123  0.003804
94   0.036967  0.031595  0.931438
95   0.984421  0.015390  0.000189
96   0.998483  0.001201  0.000316
97   0.001064  0.998475  0.000460
98   0.001038  0.998275  0.000688
99   0.022322  0.976292  0.001385
100  0.007953  0.000795  0.991252
101  0.006979  0.000494  0.992527
102  0.004170  0.992492  0.003339
103  0.000862  0.998651  0.000487
104  0.012039  0.117393  0.870568
105  0.019633  0.004934  0.975433
106  0.006921  0.988683  0.004396
107  0.988391  0.006628  0.004981
108  0.009308  0.020560  0.970132
109  0.989985  0.007614  0.002402
110  0.025476  0.974510  0.000014
111  0.004185  0.994548  0.001267
112  0.014024  0.985124  0.000852
113  0.002611  0.995863  0.001526
114  0.999499  0.000439  0.000062
115  0.997250  0.002143  0.000607
116  0.994637  0.002205  0.003158
117  0.009114  0.990082  0.000804
118  0.010501  0.988084  0.001415
119  0.032414  0.908262  0.059324
120  0.998416  0.000871  0.000713
121  0.003093  0.995533  0.001374
122  0.007734  0.013674  0.978592

[123 rows x 3 columns]